services:
  - type: web
    name: projeto-mobile-app-1
    runtime: python
    rootDir: apps/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
